CREATE TABLE DietAsist.`user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(200) DEFAULT NULL,
  `fullname` varchar(100) DEFAULT NULL,
  `estado_validacion` varchar(20) DEFAULT NULL,
  `profile_photo` varchar(200) DEFAULT NULL,
  `age` int DEFAULT NULL,
  `gender` varchar(20) DEFAULT NULL,
  `size` int DEFAULT NULL,
  `weight` int DEFAULT NULL,
  `physical_activity` varchar(50) DEFAULT NULL,
  `meal_frequency` int DEFAULT NULL,
  `hypertension` tinyint(1) DEFAULT NULL,
  `glycosylated_hemoglobin` float(3,1) DEFAULT NULL,
  `triglyceride` int DEFAULT NULL,
  `cholesterol_total` int DEFAULT NULL,
  `cholesterol_LDL` int DEFAULT NULL,
  `urid_acid` float(3,1) DEFAULT NULL,
  `calories_intake` int DEFAULT NULL,
  `carbohydrate_required` int DEFAULT NULL,
  `protein_required` int DEFAULT NULL,
  `totalfat_required` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb3;
